name: syscall
author: Kenneth Endfinger <kaendfinger@gmail.com>
homepage: https://github.com/DirectMyFile/syscall
description: Make calls to native code
version: 0.3.0
dependencies:
  binary_interop: ">=0.0.19 <0.1.0"
  binary_marshalling: ">=0.0.2 <0.1.0"
  unsafe_extension: ">=0.0.12 <0.0.15"
  binary_types: ">=0.0.50 <0.0.51"
transformers:
- $dart2js:
    $exclude: "**"
