name: syscall
author: Kenneth Endfinger <kaendfinger@gmail.com>
homepage: https://github.com/DirectMyFile/syscall
description: Make System Calls
version: 0.3.0
dependencies:
  binary_interop: ">=0.0.19 <0.1.0"
  binary_marshalling: ">=0.0.2 <0.1.0"
transformers:
- $dart2js:
    $exclude: "**"
